spring:  
    profiles: 
        active: dev
---            
server:
  port: 8001
mybatis:
  type-aliases-package: com.xuexi.pojo
  mapper-locations: classpath:mapper/DeptMapper.xml
  configuration:
    cache-enabled: true  #二级缓存
spring:
  profiles: dev
  application:
    name: cloud-config-provider-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5  # 初始化连接数
      max-total: 5  # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
logging:
  level:
     com:
       xuexi:
         mybatis: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: hf-itheima-cloud-provider:8001 #修改别名
    prefer-ip-address: true #显示IP地址
info:
 app.name: cloud-provider
 company.name: www.xuexi.com
 build.artifactId: ${project.artifactId}
 build.version: ${project.version}

--- 
server:
  port: 8002
mybatis:
  type-aliases-package: com.xuexi.pojo
  mapper-locations: classpath:mapper/DeptMapper.xml
  configuration:
    cache-enabled: true  #二级缓存
spring:
  profiles: test
  application:
    name: cloud-config-provider-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddb01?characterEncoding=utf-8
    username: root
    password: 123456
    dbcp2:
      min-idle: 5 # 数据库连接池的最小维持连接数
      initial-size: 5  # 初始化连接数
      max-total: 5  # 最大连接数
      max-wait-millis: 200 # 等待连接获取的最大超时时间
logging:
  level:
     com:
       xuexi:
         mybatis: debug
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka,http://localhost:7002/eureka,http://localhost:7003/eureka
  instance:
    instance-id: hf-itheima-cloud-provider:8001 #修改别名
    prefer-ip-address: true #显示IP地址
info:
 app.name: cloud-provider
 company.name: www.xuexi.com
 build.artifactId: ${project.artifactId}
 build.version: ${project.version}                    #显示IP地址